// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	RoomId string `path:"roomId"`
}

type Response struct {
	Urls    []string `json:"urls"`
	Name    string   `json:"name"`
	LiveUrl string   `json:"liveUrl"`
}
